"""first

Revision ID: 1ad2869994da
Revises: 
Create Date: 2021-01-20 20:17:39.512425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ad2869994da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamedata',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('is_year_setup', sa.Boolean(), nullable=True),
    sa.Column('is_year_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('gamerules',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('can_tie', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('home_team_id', sa.String(), nullable=True),
    sa.Column('away_team_id', sa.String(), nullable=True),
    sa.Column('rules_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.oid'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.oid'], ),
    sa.ForeignKeyConstraint(['rules_id'], ['gamerules.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('records',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('gamerules')
    op.drop_table('gamedata')
    # ### end Alembic commands ###
