"""second

Revision ID: d92f3ff5fdd7
Revises: 1ad2869994da
Create Date: 2021-12-28 07:20:59.140778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92f3ff5fdd7'
down_revision = '1ad2869994da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('type', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'type')
    op.drop_column('records', 'type')
    # ### end Alembic commands ###
