"""Test

Revision ID: 138252a3c7bf
Revises: 
Create Date: 2021-01-17 13:01:16.005021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138252a3c7bf'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('gamerules')
    op.drop_table('teams')
    op.drop_table('games')
    op.drop_table('configuration')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('games',
    sa.Column('oid', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('home_score', sa.INTEGER(), nullable=True),
    sa.Column('away_score', sa.INTEGER(), nullable=True),
    sa.Column('complete', sa.INTEGER(), nullable=True),
    sa.Column('processed', sa.INTEGER(), nullable=True),
    sa.Column('home_team_id', sa.INTEGER(), nullable=True),
    sa.Column('away_team_id', sa.INTEGER(), nullable=True),
    sa.Column('rules_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.oid'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.oid'], ),
    sa.ForeignKeyConstraint(['rules_id'], ['gamerules.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('teams',
    sa.Column('oid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('skill', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gamerules',
    sa.Column('oid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('can_tie', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('records',
    sa.Column('oid', sa.VARCHAR(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('wins', sa.INTEGER(), nullable=True),
    sa.Column('loses', sa.INTEGER(), nullable=True),
    sa.Column('ties', sa.INTEGER(), nullable=True),
    sa.Column('goals_for', sa.INTEGER(), nullable=True),
    sa.Column('goals_against', sa.INTEGER(), nullable=True),
    sa.Column('skill', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.oid'], ),
    sa.PrimaryKeyConstraint('oid')
    )
    # ### end Alembic commands ###
