"""active

Revision ID: 308811b170ff
Revises: 138252a3c7bf
Create Date: 2021-01-17 13:12:21.630425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308811b170ff'
down_revision = '138252a3c7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'active')
    # ### end Alembic commands ###
