from teams.domain.base import Base
from teams.domain.competition import Competition
from teams.domain.competition_game import CompetitionGame
from teams.domain.competition_group import CompetitionGroup
from teams.domain.competition_ranking import CompetitionRanking
from teams.domain.competition_team import CompetitionTeam
from teams.domain.game import Game
from teams.domain.game_rules import GameRules
from teams.domain.gamedata import GameData
from teams.domain.record import Record
from teams.domain.series import Series
from teams.domain.series_by_goals import SeriesByGoals
from teams.domain.series_by_goals_rules import SeriesByGoalsRules
from teams.domain.series_by_wins import SeriesByWins
from teams.domain.series_by_wins_rules import SeriesByWinsRules
from teams.domain.series_game import SeriesGame
from teams.domain.series_rules import SeriesRules
from teams.domain.sub_competition import SubCompetition
from teams.domain.table_sub_competition import TableSubCompetition
from teams.domain.playoff_sub_competition import PlayoffSubCompetition
from teams.domain.table_record import TableRecord
from teams.domain.team import Team
# check each of these to see if they are fully mapped
from teams.domain.competition_configuration import CompetitionConfiguration
from teams.domain.competition_group_configuration import CompetitionGroupConfiguration
from teams.domain.sub_competition_configuration import SubCompetitionConfiguration
from teams.domain.playoff_sub_competition_configuration import PlayoffSubCompetitionConfiguration
from teams.domain.table_sub_competition_configuration import TableSubCompetitionConfiguration
from teams.domain.competition_team_configuration import CompetitionTeamConfiguration
from teams.domain.series_configuration import SeriesConfiguration
from teams.domain.table_game_configuration import TableGameConfiguration

